devtools::document("~/git/staticdocs")
devtools::install("~/git/staticdocs")
library(staticdocs)

debug(staticdocs:::to_html.list)
debug(staticdocs:::to_html.Rd_doc)
debug(staticdocs:::to_html.examples)
debug(staticdocs:::replay_html)
debug(staticdocs:::replay_html.recordedplot)
build_site("~/git/mkin", site_path = "~/svn/kinfit.r-forge/www/mkin_static")
