RBIN ?= $(shell dirname "`which R`")

all: vignettes

%.pdf: header.tex references.bib %.Rnw
	"$(RBIN)/Rscript" -e "tools::buildVignette(file = '$*.Rnw')"

%.html: mkin_vignettes.css %.Rmd
	"$(RBIN)/Rscript" -e "tools::buildVignette(file = '$*.Rmd')"

vignettes: mkin.pdf FOCUS_D.html FOCUS_L.html FOCUS_Z.pdf compiled_models.html

clean: 
	$(RM) *.aux *.bbl *.blg *.fdb_latexmk *.fls *.log *.out *.toc
	$(RM) *.R *.md
	$(RM) mkin.tex FOCUS_Z.tex
	$(RM) -r *_cache *_files
	$(RM) -r figure cache
