---
title: Calculation of time weighted average concentrations with mkin
author: Johannes Ranke
date: "`r Sys.Date()`"
bibliography: references.bib
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Calculation of time weighted average concentrations with mkin}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

Since version 0.9.45.1 of the 'mkin' package, a function for calculating
time weighted average concentrations for decline kinetics (*i.e.* only
for the compound applied in the experiment) is included. Strictly
speaking, they are maximum moving window time weighted average concentrations,
*i.e.* the maximum time weighted average concentration that can be found
when moving a time window of a specified width over the decline curve.

Time weighted average concentrations for the SFO, FOMC and the DFOP model are
calculated using the formulas given in the FOCUS kinetics guidance
[@FOCUSkinetics2014, p. 251]:

SFO:

$$c_\textrm{twa} = c_0 \frac{\left( 1 - e^{- k t} \right)}{ k t} $$

FOMC:

$$c_\textrm{twa} = c_0 \frac{\beta}{t (1 - \alpha)}
                   \left( \left(\frac{t}{\beta} + 1 \right)^{1 - \alpha} - 1 \right) $$

DFOP:

$$c_\textrm{twa} = \frac{c_0}{t} \left(
  \frac{g}{k_1} \left( 1 - e^{- k_1 t} \right) +
  \frac{1-g}{k_2} \left( 1 - e^{- k_2 t} \right)  \right) $$

HS for $t > t_b$:

$$c_\textrm{twa} = \frac{c_0}{t} \left(
  \frac{1}{k_1} \left( 1 - e^{- k_1 t_b} \right) +
  \frac{e^{- k_1 t_b}}{k_2} \left( 1 - e^{- k_2 (t - t_b)} \right)  \right) $$

Often, the ratio between the time weighted average concentration $c_\textrm{twa}$
and the initial concentration $c_0$

$$f_\textrm{twa} = \frac{c_\textrm{twa}}{c_0}$$

is needed. This can be calculated from the fitted initial concentration $c_0$ and
the time weighted average concentration $c_\textrm{twa}$, or directly from
the model parameters using the following formulas:

SFO:

$$f_\textrm{twa} = \frac{\left( 1 - e^{- k t} \right)}{k t} $$

FOMC:

$$f_\textrm{twa} = \frac{\beta}{t (1 - \alpha)}
                   \left( \left(\frac{t}{\beta} + 1 \right)^{1 - \alpha} - 1 \right) $$

DFOP:

$$f_\textrm{twa} = \frac{1}{t} \left(
  \frac{g}{k_1} \left( 1 - e^{- k_1 t} \right) +
  \frac{1-g}{k_2} \left( 1 - e^{- k_2 t} \right)  \right) $$

HS for $t > t_b$:

$$f_\textrm{twa} = \frac{1}{t} \left(
  \frac{1}{k_1} \left( 1 - e^{- k_1 t_b} \right) +
  \frac{e^{- k_1 t_b}}{k_2} \left( 1 - e^{- k_2 (t - t_b)} \right)  \right) $$

Note that a method for calculating maximum moving window time weighted average
concentrations for any model fitted by 'mkinfit', and also for metabolites in
such models, is integrated in the 'mkin' package, see the
[documentation](https://pkgdown.jrwb.de/pfm/reference/max_twa_parent.html) at my website.
